[gateway]
node1 ansible_host=192.168.1.202 wg_ip=10.0.0.1 listen_port=51820 dns=1.1.1.1

[nodes]
node0 ansible_host=192.168.1.201 wg_ip=10.0.0.2
labserver ansible_host=192.168.1.100 wg_ip=10.0.0.3

[gateway:vars]
ansible_user=root

[nodes:vars]
ansible_user=root
