[all:vars]
# listen_port is port that nodes and gateway uses.
listen_port=23122
network_mask=24

# [gateway] section for setting vpn's gateway args(ip/domain , vpn ip)
[gateway]
# ONLY ONE GATEWAY DURING THE USAGE CYCLE,
# In gateway case ansible_host also are endpoint -> files/wg0-n.conf
#
#					U can set any net u want for VPN. 
#					In this case its 10.0.0.1/24
#					
#					  V
# node1 ansible_host=192.168.1.202 wg_ip=10.0.0.1 
node_gw ansible_host=192.168.1.2 wg_ip=10.0.0.1 


# [nodes] section for setting vpn's nodes args
[nodes]
#	name of host uses in keys' names 
#	./files/{hostname}_public
#
# can be literally any name as u want(prefer hostname or domain) for better usage
# |
# |
# |
# |					
# |	node's ip/domain via playbooks 	node's ip in VPN -> files/wg0*.conf
# |	gets access	|		|
# V	    		V		V
# node0 ansible_host=192.168.1.2 wg_ip=10.0.0.2 
node0 ansible_host=192.168.1.201 wg_ip=10.0.0.2
node1 ansible_host=192.168.1.202 wg_ip=10.0.0.3 
node3 ansible_host=192.168.1.203 wg_ip=10.0.0.4
gitlab ansible_host=192.168.1.204 wg_ip=10.0.0.6


[gateway:vars]
ansible_user=root
interface=wg0-gw

#The gateway interface through which 
#nodes is accessed -> wg0-gw.conf
gateway_interface = eth0


[nodes:vars]
ansible_user=root
interface=wg0-n
