[Interface]
Address = {{ wg_ip }}/32
PrivateKey = {{ node_pri['stdout'] }}
ListenPort = {{ listen_port }}

[Peer]
Endpoint = {{ hostvars[groups['gateway'][0]].ansible_host }}:{{ listen_port }}
Publickey = {{ gw_pub }}
AllowedIps = 0.0.0.0/0
PersistentKeepalive = 25
