[Interface]
Address = {{ wg_ip }}/{{ network_mask }}
ListenPort = {{ listen_port }}
PrivateKey = {{ gw_pri['stdout'] }}
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -m state --state ESTABLISHED,RELATED -j ACCEPT; iptables -t nat -A POSTROUTING -o {{ gateway_interface }} -j MASQUERADE 
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -m state --state ESTABLISHED,RELATED -j ACCEPT; iptables -t nat -D POSTROUTING -o {{ gateway_interface }} -j MASQUERADE
