- hosts: gateway

  tasks:
    - name: Add [Peer] blocks in wg0-gw.conf
      ansible.builtin.blockinfile:
        path: /etc/wireguard/wg0-gw.conf
        insertafter: EOF
        block: |
          [Peer]
          PublicKey = {{ lookup('file', '../files/public_keys/' ~item ~ '_public') }}
          AllowedIps = {{ hostvars[item].wg_ip }}/32
        marker: "# {mark} for {{ item }}"
      loop: "{{ groups['nodes'] }}"
    - name: Restart wg-quick
      ansible.builtin.systemd:
        name: "{{service}}"
        state: restarted
