- name: configure wireguard nodes
  hosts: nodes
  become: yes

  tasks:
    - name: Generate private
      ansible.builtin.shell: |
        umask 077
        wg genkey > /etc/wireguard/{{inventory_hostname}}_private
        cat /etc/wireguard/{{inventory_hostname}}_private
      register: node_pri

    - name: Generate public
      ansible.builtin.shell: |
        wg pubkey <  /etc/wireguard/{{inventory_hostname}}_private > /etc/wireguard/{{inventory_hostname}}_public
        cat /etc/wireguard/{{inventory_hostname}}_public
      register: node_pub

    - name: Read gateway public key
      ansible.builtin.set_fact:
        gw_pub: "{{ lookup('file', '../files/gateway_public') }}"

    - name: Create wg0-n.conf
      ansible.builtin.template:
        src: ../files/wg0-n.conf
        dest: /etc/wireguard/wg0-n.conf

    - name: Copy public key from node to controller
      ansible.builtin.fetch:
        src: /etc/wireguard/{{inventory_hostname}}_public
        dest: ../files/{{inventory_hostname}}_public
        flat: yes
