
- name: general tasks
  hosts: all
  become: yes
  tasks:
    - name: Install epel-release
      ansible.builtin.package:
        name: epel-release
        state: present
      when: ansible_facts["os_family"] == "RedHat"

    - name: Install  wg
      ansible.builtin.package:
        name: wireguard-tools
        state: present
        update_cache: yes
